// Generating a random word association (cadavre exquis) to display in front-end
const word = {
  ExWords: [
    "Explosion",
    "Expérience",
    "Exfoliant",
    "Ex",
    "Exigences",
    "Ex-utero",
    "Expat'",
    "Exutoire",
    "Exclusion",
    "Excision",
    "Existance",
    "Excellent",
    "Excitation",
    "Excrément",
    "Exil",
  ],

  PWords: [
    "paisible",
    "pareil",
    "pareille",
    "paresseux",
    "parfait",
    "passable",
    "pauvre",
    "pénible",
    "permanent",
    "permanente",
    "personnel",
    "personnelle",
    "pessimiste",
    "petit",
    "piquant",
    "pire",
    "plaire",
    "plat",
    "plein",
    "pleine",
    "pointu",
    "poli",
    "polisson",
    "possible",
    "pratique",
    "précieux",
    "précis",
    "premier",
    "présent",
    "prêt",
    "prioritaire",
    "privé",
    "proche",
    "profond",
    "prudent",
    "puissant",
    "pur",
  ],
};

let ExWordRandom = Math.floor(Math.random() * word.ExWords.length);
let PWordRandom = Math.floor(Math.random() * word.PWords.length);
let cadExp = `${word.ExWords[ExWordRandom]} ${word.PWords[PWordRandom]}`;
document.getElementById("cadex").textContent = `(${cadExp})`;
